# Expõe todos os endpoints do Actuator via HTTP
management.endpoints.web.exposure.include=*

# Mostra detalhes extras no endpoint de health (como status do banco, disco, etc)
management.endpoint.health.show-details=always
